### ISSUE TITLE
rollup error during npm build on Ubuntu

### ISSUE THREAD

**Issue by turbobobbytraykov** [IgniteUI/grid-demos#14]
When running npm run build on Ubuntu 22.04 we get the following error:

> An unhandled exception occurred: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
> See "/tmp/ng-YUWFiC/angular-errors.log" for further details.

**Comment by turbobobbytraykov** [comment]
As noted in https://github.com/vitejs/vite/discussions/15532, we may need to add this to the package.lock.json file:

>   "optionalDependencies": {
>       "@rollup/rollup-linux-x64-gnu": "4.26.0"
>     }

However since this is a transient dependency, I am not sure if this is the right way to go.
